### ISSUE TITLE
Separate Screens for Success and Failure

### ISSUE THREAD

**Issue by OwenM4** [passiondynamics/cast-le-frontend#11]
**Points:** 2

**TODOs:**
- [ ] Build an obvious success screen 
- [ ] Build and obvious fail screen
- [ ] Write code to make the proper screen appear when necessary

**Description:** Build clearer screens for a success and a failure.

**Notes:** I cannot tell when I succeed and when I fail and I know the answer...
